// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using huisbot.Persistence;

#nullable disable

namespace huisbot.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20231116185108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("huisbot.Models.Utility.OsuDiscordLink", b =>
                {
                    b.Property<ulong>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_id");

                    b.Property<int>("OsuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("osu_id");

                    b.HasKey("DiscordId")
                        .HasName("pk_osu_discord_links");

                    b.ToTable("osu_discord_links", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
