// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using huisbot.Persistence;

#nullable disable

namespace huisbot.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240727104618_RenameScoreToResponse")]
    partial class RenameScoreToResponse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("huisbot.Models.Persistence.BeatmapAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<long>("BeatmapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beatmap_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.HasKey("Alias")
                        .HasName("pk_beatmap_aliases");

                    b.ToTable("beatmap_aliases", (string)null);
                });

            modelBuilder.Entity("huisbot.Models.Persistence.CachedScoreSimulation", b =>
                {
                    b.Property<string>("RequestIdentifier")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_identifier");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response_json");

                    b.HasKey("RequestIdentifier")
                        .HasName("pk_cached_score_simulations");

                    b.ToTable("cached_score_simulations", (string)null);
                });

            modelBuilder.Entity("huisbot.Models.Persistence.OsuDiscordLink", b =>
                {
                    b.Property<ulong>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_id");

                    b.Property<int>("OsuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("osu_id");

                    b.HasKey("DiscordId")
                        .HasName("pk_osu_discord_links");

                    b.ToTable("osu_discord_links", (string)null);
                });

            modelBuilder.Entity("huisbot.Models.Persistence.ScoreAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("ScoreId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_id");

                    b.HasKey("Alias")
                        .HasName("pk_score_aliases");

                    b.ToTable("score_aliases", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
